version: "3.7"
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER_FILE: '/run/secrets/mysql-user'
      MYSQL_DATABASE_FILE: '/run/secrets/mysql-database'
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
    secrets:
      - mysql-user
      - mysql-database
      - mysql-password
    networks:
      - lan
      - web
    volumes:
      - db:/var/lib/mysql

  blog:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER_FILE: '/run/secrets/mysql-user'
      WORDPRESS_DB_PASSWORD_FILE: '/run/secrets/mysql-password'
      WORDPRESS_DB_NAME_FILE: '/run/secrets/mysql-database'
    secrets:
      - mysql-user
      - mysql-database
      - mysql-password
    networks:
      - lan
      - web
    working_dir: /var/www/html
    volumes:
      - ~/html:/var/www/html:rw
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw

    labels:
      traefik.enable: true
      traefik.docker.network: web
      traefik.http.routers.wordpress.entrypoints: https
      traefik.http.routers.wordpress.rule: 'Host(`wordpress.myip.myip.com`)'
      traefik.http.services.wordpress.loadbalancer.server.port: 80
      traefik.http.routers.wordpress-admin.rule: 'Host(`wordpress.myip.myip.com`) && (Path(`/wp-admin`)|| Path(`/wp-login.php`))'

      traefik.http.routers.wordpress.tls: true
      traefik.http.routers.wordpress.tls.certresolver: http

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER_FILE: '/run/secrets/mysql-user'
      MYSQL_DATABASE_FILE: '/run/secrets/mysql-database'
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
    ports:
      - "8180:80"
    restart: always

volumes:
  db:
  html:

networks:
  web:
    external: true
