global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:8080']
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: "mongo"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-wordpress-exporter:9104"]


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
