version: '3.7'
services:


    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad
        restart: unless-stopped
        networks:
            meet.jitsi:
                aliases:
